name: Test
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: tresas-sportsbet/hello-world-docker-action-tresan@v1
        with:
          who-to-greet: '@tresas-sportsbet'
